###auth app routes ******

@auth_url= http://localhost:3001/api

### retrive all users
GET  {{auth_url}}/users


### login
POST {{auth_url}}/login
Content-Type: application/json

{
    "username":"bakr",
    "password":"123456"
}

### orders app routes ******

@orders_url= http://localhost:4000/orders

GET  {{orders_url}}/all


###bills app routes ******

@bills_url= http://localhost:4002/bills

GET  {{bills_url}}/